//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUPE_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class classes
    {
        public int idClasse { get; set; }
        public string nom { get; set; }
    }
}
