//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUPE_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class etudiants
    {
        public int id { get; set; }
        public string matricule { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string sexe { get; set; }
        public string adresse { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public int idClasse { get; set; }
    }
}
