//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUPE_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestionDesEtudiantsEntities : DbContext
    {
        public gestionDesEtudiantsEntities()
            : base("name=gestionDesEtudiantsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classes> classes { get; set; }
        public virtual DbSet<cours> cours { get; set; }
        public virtual DbSet<etudiants> etudiants { get; set; }
        public virtual DbSet<matieres> matieres { get; set; }
        public virtual DbSet<notes> notes { get; set; }
        public virtual DbSet<OTPCodes> OTPCodes { get; set; }
        public virtual DbSet<professeurs> professeurs { get; set; }
        public virtual DbSet<utilisateurs> utilisateurs { get; set; }
        public virtual DbSet<classeCours> classeCours { get; set; }
    }
}
