//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUPE_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class notes
    {
        public int idNote { get; set; }
        public int idEtudiant { get; set; }
        public int idMatiere { get; set; }
        public Nullable<double> note { get; set; }
    }
}
