//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROUPE_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPCodes
    {
        public int idOTPCode { get; set; }
        public int idUtilisateur { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> dateExpiration { get; set; }
    }
}
